// components/forms/login-form.tsx
"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { Loader2Icon } from "lucide-react";

import Logo from "@/assets/cron_logo.png";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

import {
  createSession,
  isAlreadyAuthenticated,
} from "@/lib/session";
import { loginUser } from "@/services/user-service";

type LoginFormState = {
  email: string;
  password: string;
};

const initialState: LoginFormState = {
  email: "",
  password: "",
};

export function LoginForm() {
  const router = useRouter();

  const [isSubmitting, setSubmitting] = useState(false);

  const [form, setForm] = useState<LoginFormState>(initialState);

  useEffect(() => {
    if (isAlreadyAuthenticated()) {
      router.replace("/");
    }
  }, [router]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setForm((prev) => ({
      ...prev,
      [e.target.name]: e.target.value,
    }));
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    try {
      setSubmitting(true);

      const response = await loginUser(form);

      if (response.success) {
        createSession(response.data.token);
        router.push("/");
      }
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <Image
          src={Logo}
          alt="Logo"
          className="mx-auto mt-2 mb-6 w-30 object-cover"
        />

        <CardTitle>Login</CardTitle>

        <CardDescription>
          Enter your email below to login to your account.
        </CardDescription>
      </CardHeader>

      <CardContent>
        <form onSubmit={handleSubmit}>
          <div className="flex flex-col gap-4">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>

              <Input
                id="email"
                name="email"
                type="email"
                value={form.email}
                onChange={handleChange}
                disabled={isSubmitting}
                placeholder="Email address"
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>

              <Input
                id="password"
                name="password"
                type="password"
                value={form.password}
                onChange={handleChange}
                disabled={isSubmitting}
                placeholder="Password"
                required
              />
            </div>

            <Button
              type="submit"
              disabled={isSubmitting}
              className="mt-4 w-full cursor-pointer"
            >
              {isSubmitting && <Loader2Icon className="animate-spin" />}
              Login
            </Button>

            <div className="text-center text-sm">
              Don't have an account?{" "}
              <a
                href="/register"
                className="underline underline-offset-4"
              >
                Sign up
              </a>
            </div>
          </div>
        </form>
      </CardContent>
    </Card>
  );
}

// src/lib/components/auth/LoginForm.svelte
<script lang="ts">
    import * as Card from "$lib/components/ui/card";
    import { Label } from "$lib/components/ui/label";
    import { Input } from "$lib/components/ui/input";
    import { Button } from "$lib/components/ui/button";
    import {
        login,
        type LoginRequest,
        type LoginResponse,
    } from "$lib/services/auth";
    import { auth } from "$lib/auth/auth.svelte";
    import { type User, type ValidationErrors } from "$lib/types";
    import { goto } from "$app/navigation";
    import { resolve } from "$app/paths";
    import { loginSchema } from "$lib/auth/AuthValidationSchemas";
    import { LOGGER } from "$lib/logger";
    import { validateForm } from "$lib/utils";

    let email = $state("");
    let password = $state("");
    let loading = $state(false);
    let validationErrors = $state<ValidationErrors>({});
    let error = $state<string | undefined>("");

    async function handleLogin() {
        loading = true;
        let reqData: LoginRequest = { email, password };
        
        validationErrors = validateForm(loginSchema, reqData);
        if (Object.keys(validationErrors).length > 0) {
            LOGGER.error("Validation error", Object.entries(validationErrors));
            loading = false;
            return;
        }

        const resp: LoginResponse = await login(reqData);
        if (resp.status == 200) {
            error = undefined;
            if (resp.data?.auth_token && resp.data) {
                auth.authenticate(resp.data.auth_token, resp.data as User);
                goto(resolve("/"));
            }
        } else {
            error = resp.message;
        }
        loading = false;
        return;
    }
</script>

<Card.Root>
    <Card.Header>
        <Card.Title>Login</Card.Title>
        <Card.Description>Sign in to your account</Card.Description>
    </Card.Header>

    <Card.Content class="space-y-4 min-w-xs">
        <div class="space-y-2">
            <Label for="email">Email</Label>
            <Input
                id="email"
                type="email"
                placeholder="Enter your email"
                bind:value={email}
                required
            />
            {#if validationErrors.email}
                <p class="text-destructive text-xs">{validationErrors.email}</p>
            {/if}
        </div>

        <div class="space-y-2">
            <Label for="password">Password</Label>

            <Input
                id="password"
                type="password"
                placeholder="Enter your password"
                bind:value={password}
                required
            />
            {#if validationErrors.password}
                <p class="text-destructive text-xs">{validationErrors.password}</p>
            {/if}
        </div>

        {#if error}
            <p class="text-destructive text-xs">{error}</p>
        {/if}
    </Card.Content>

    <Card.Footer>
        <div class="flex flex-col w-full space-y-4 text-center">
            <Button class="w-full hover:cursor-pointer" disabled={loading} onclick={handleLogin}>
                {loading ? "Signing In..." : "Login"}
            </Button>
            <a href={resolve("/register")}>Don't have an account?</a>
        </div>
    </Card.Footer>
</Card.Root>
